package jsw.report.viewBean;
// Generated Jan 4, 2017 6:13:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Approver generated by hbm2java
 */
@Entity
@Table(name = "approver", catalog = "lapp")
public class Approver implements java.io.Serializable {

	private int id=0;
	private String userName;
	private String approverName;
	private String backupName;

	public Approver() {
	}

	public Approver(int id, String userName, String approverName, String backupName) {
		this.id = id;
		this.userName = userName;
		this.approverName = approverName;
		this.backupName = backupName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "approver_name", nullable = false, length = 50)
	public String getApproverName() {
		return this.approverName;
	}

	public void setApproverName(String approverName) {
		this.approverName = approverName;
	}

	@Column(name = "backup_name", nullable = false, length = 50)
	public String getBackupName() {
		return this.backupName;
	}

	public void setBackupName(String backupName) {
		this.backupName = backupName;
	}

}
