package jsw.report.viewBean;
// default package
// Generated Jan 12, 2017 2:59:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChatSummary generated by hbm2java
 */
@Entity
@Table(name = "chat_summary", catalog = "chat")
public class ChatSummary implements java.io.Serializable {

	private Integer id;
	private String message;
	private String direction;
	private int isDisplayedToUser;
	private Date createdTime;

	public ChatSummary() {
	}

	public ChatSummary(String message, String direction, int isDisplayedToUser, Date createdTime) {
		this.message = message;
		this.direction = direction;
		this.isDisplayedToUser = isDisplayedToUser;
		this.createdTime = createdTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message", nullable = false, length = 50)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "direction", nullable = false, length = 50)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "is_displayed_to_user", nullable = false)
	public int getIsDisplayedToUser() {
		return this.isDisplayedToUser;
	}

	public void setIsDisplayedToUser(int isDisplayedToUser) {
		this.isDisplayedToUser = isDisplayedToUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Override
	public String toString() {
		return "ChatSummary [id=" + id + ", message=" + message + ", direction=" + direction + ", isDisplayedToUser="
				+ isDisplayedToUser + ", createdTime=" + createdTime + "]";
	}

}
