package jsw.report.viewBean;


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class RegistrationBean implements java.io.Serializable {

	private Integer id;
	private String usename;
	private String password;
	private String name;
	private String email;
	private String gender;
	private String nationality;
	private String passportNo;
	private String issueDate;
	private String expiryDate;
	private String actor;
	private String dashboard;
	private String role;
private String screenId;



	public String getScreenId() {
	return screenId;
}

public void setScreenId(String screenId) {
	this.screenId = screenId;
}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getDashboard() {
		return dashboard;
	}

	public void setDashboard(String dashboard) {
		this.dashboard = dashboard;
	}

	public RegistrationBean() {
	}

	public RegistrationBean(String usename, String password, String name, String email, String gender) {
		this.usename = usename;
		this.password = password;
		this.name = name;
		this.email = email;
		this.gender = gender;
	}

	public RegistrationBean(String usename, String password, String name, String email, String gender, String nationality,
			String passportNo, String issueDate, String expiryDate, String active, String actor) {
		this.usename = usename;
		this.password = password;
		this.name = name;
		this.email = email;
		this.gender = gender;
		this.nationality = nationality;
		this.passportNo = passportNo;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
		this.actor = actor;
	
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsename() {
		return this.usename;
	}

	public void setUsename(String usename) {
		this.usename = usename;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}



	public String getActor() {
		return this.actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	@Override
	public String toString() {
		return "RegistrationBean [id=" + id + ", usename=" + usename + ", password=" + password + ", name=" + name
				+ ", email=" + email + ", gender=" + gender + ", nationality=" + nationality + ", passportNo="
				+ passportNo + ", issueDate=" + issueDate + ", expiryDate=" + expiryDate + ", actor=" + actor
				+ ", screenId=" + dashboard + "]";
	}

	

}
