package jsw.report.viewBean;
// default package
// Generated Jan 5, 2017 4:20:05 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", catalog = "lapp")
public class Scheme implements java.io.Serializable {

	private int id;
	
	private String type,description,productName;
	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	private String discount;
	
	
	private String fromDate;
	private String toDate;
	private String isActive;

	public Scheme() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDiscount() {
		return discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getIsActive() {
		return isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public Scheme(int id, String type, String description, String discount, String fromDate, String toDate,
			String isActive) {
		super();
		this.id = id;
		this.type = type;
		this.description = description;
		this.discount = discount;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.isActive = isActive;
	}

	

	

	

}
