package jsw.report.viewBean;
// default package
// Generated Jan 3, 2017 10:29:02 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usermachineaccess generated by hbm2java
 */
@Entity
@Table(name = "usermachineaccess", catalog = "volkswagen")
public class Usermachineaccess implements java.io.Serializable {

	private int id;
	private int userId;
	private String ovenId;
	private String chamberId;
	private String isActive;
	private String createdBy;
	private String createdDate;
	private String updatedBy;
	private String updatedDate;

	public Usermachineaccess() {
	}

	public Usermachineaccess(int id, int userId, String ovenId, String chamberId, String isActive, String createdBy,
			String createdDate, String updatedBy, String updatedDate) {
		this.id = id;
		this.userId = userId;
		this.ovenId = ovenId;
		this.chamberId = chamberId;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "oven_id", nullable = false, length = 50)
	public String getOvenId() {
		return this.ovenId;
	}

	public void setOvenId(String ovenId) {
		this.ovenId = ovenId;
	}

	@Column(name = "chamber_id", nullable = false, length = 50)
	public String getChamberId() {
		return this.chamberId;
	}

	public void setChamberId(String chamberId) {
		this.chamberId = chamberId;
	}

	@Column(name = "isActive", nullable = false, length = 50)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", nullable = false, length = 50)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false, length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", nullable = false, length = 50)
	public String getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}

}
